### ISSUE TITLE
Ox version 8 syntax change

### ISSUE THREAD

**Issue by ferrall** [yozw/oxdoc#11]
Ox  8 has a new syntax: The three dots in a function header, indicating variable number of arguments, can now be followed by a variable name. E.g:
		func(...**args**)
		{
			decl a = 1;
		}
is convenient shorthand for
		func(...)
		{
			decl args = va_arglist();
			decl a = 1;
		}
Oxdoc gives up with an error if this is encountered.

**Comment by yozw** [comment]
https://github.com/yozw/oxdoc/commit/6bac51bd9311a29b6ef96948cbe3fca6b6473b65 should fix this.
