### ISSUE TITLE
Matrix constant creation

### ISSUE THREAD

**Issue by ferrall** [yozw/oxdoc#12]
Some aspect of Ox's syntax for creating matrix constants is not recognized by OxDoc (which stops processing the file when encountered).

The form that creates the problem is repeated values:
enum{Vleng=3}
static decl zerovector < [Vleng] *0>;

It other words, this will repeat "0" a total of 3 times in the vector.  It is equivalent to <0,0,0>.

**Comment by yozw** [comment]
Do you have time address these issues? I haven't used oxdoc in over 10 years, and don't feel particularly motivated anymore to do any further work on it ...

**Comment by ferrall** [comment]
Yori,

I completely understand.  I didn't expect you to respond.  My very limited understanding of Java keeps me from making these changes, although at some point I might get a student to help me.

In the meantime I use a pre-compiler directive to comment out the new syntax in my code so that it is skipped by OxDoc but not Ox.  So far that works.

--C

On 22/03/2019 7:42 PM, Yori Zwols wrote:

Do you have time address these issues? I haven't used oxdoc in over 10 years, and don't feel particularly motivated anymore to do any further work on it ...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyozw%2Foxdoc%2Fissues%2F12%23issuecomment-475816883&data=02%7C01%7Cferrallc%40queensu.ca%7C60c1ad44d2f944d7e5b208d6af2008a4%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C636888949448543941&sdata=7wlnm7iQXSEz7675eM0BouJwbJDwuBedUFqXWX56TNw%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHTgpKI5plajOBWV521-Cs5XLu3hiaDGks5vZWpfgaJpZM4cAVtZ&data=02%7C01%7Cferrallc%40queensu.ca%7C60c1ad44d2f944d7e5b208d6af2008a4%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C636888949448543941&sdata=a%2FJ79J1AKJfcdZ4FRb7w6MQNNYJCq5%2FgWcEtfwCXxgg%3D&reserved=0>.

--

==========================================
Christopher Ferrall
Professor of Economics
Queen's University
613-533-6658
econ.queensu.ca/pub/faculty/ferrall
==========================================

**Comment by yozw** [comment]
https://github.com/yozw/oxdoc/commit/4726e5adbc45ec6db4f50e6694b428be92c70820 should fix the issue.
