### ISSUE TITLE
include latex commands

### ISSUE THREAD

**Issue by linc0380** [yozw/oxdoc#14]
I have the following option set in my `oxdoc.xml`:
```
<option latexpackages="unicode-math,eucal"/>
```
How can one pass through package specifics, for instance the command
```
\setmathfont{...}
```
for `unicode-math` or the option
```
\usepackage[mathscr]{eucal}
```

**Comment by yozw** [comment]
Oxdoc doesn't support that, but you can easily create your own package, say `oxdoc.sty`:

```
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{oxdoc}[2023/08/10 Example package]

\RequirePackage[mathscr]{eucal}
\setmathfont{...}
```

**Comment by yozw** [comment]
Ah, the latex gets compiled in a temporary directory, and your new package doesn't get copied into that temporary directory. 

How important is it for you to rely on latex compilation anyway? Can you not just rely on MathJax for formulas? That tends to look a lot better. (It didn't exist back in 2004, otherwise I would have only supported MathJax).

**Comment by yozw** [comment]
Maybe https://tex.stackexchange.com/questions/632291/add-search-path-on-compilation does the trick for you?

**Comment by linc0380** [comment]
Sorry, I think I have been completely confused about the difference between my own tex installation and MathJax!

For using LaTeX in Oxdoc, my `oxdoc.xml` now includes the following lines:
```
<option formulas="latex"/> 
<option latex="/usr/bin/latex"/>
<option dvipng="/usr/bin/dvipng"/>
<option latexpackages="oxdoctex"/>
```
where my new package `oxdoctex.sty` resides in my `TEXINPUTS` path and is duly found upon compilation. Yet, as you mention, the resulting images are of a low resolution and are not properly aligned with the text. Is there an easy way in OxDoc to improve the one and/or the other issue?

For using MathJax with Oxdoc, the above four options in `oxdoc.xml` are reduced to a single line: 
```
<option formulas="mathjax"/>
```
The option `<option latexpackages="oxdoctex"/>` does not seem to have an effect. I fear this is because MathJax cannot be (easily?) extended? I have not yet thought a great deal about MathJax but am wondering how commands such as `\coloneqq` command in the `mathtools` package could be used?

**Comment by yozw** [comment]
Yes, latex image rendering in inferior to MathJax. I highly recommend using MathJax.

MathJax has a mathtools extension: https://docs.mathjax.org/en/latest/input/tex/extensions/mathtools.html. 

I'll add a mechanism to inject MathJax options.

**Comment by yozw** [comment]
I've added functionality to include custom javascript in https://github.com/yozw/oxdoc/commit/b7babfca23a354948d78dffc5b98f2f4bab9182f. For an example, see https://github.com/yozw/oxdoc/tree/master/example.

**Comment by linc0380** [comment]
That's brilliant! 

How would `oxdoc.js` have to look like if I wanted to include two (or more) MathJax extensions? Would I include a _second_ block such as
```
window.MathJax = {
  loader: {load: ['[tex]/cases']},
  tex: {packages: {'[+]': ['cases']}}
};
```
or is there a way in Java to specify a list of packages in _one_ block?

**Comment by yozw** [comment]
My guess is something like

```
window.MathJax = {
  loader: {load: ['[tex]/cases', '[tex]/mathtools']},
  tex: {packages: {'[+]': ['cases', 'mathtools']}}
};
```

But you may want to have a look the MathJax documentation instead.

**Comment by linc0380** [comment]
That works perfectly! Thanks a lot!

I could not find an appropriate sample snippet on the MathJax site. Here is one in the context of excluding LaTeX packages, yet it still requires some guesswork: [https://docs.mathjax.org/en/latest/input/tex/extensions.html](url)
