### ISSUE TITLE
database class function Info()

### ISSUE THREAD

**Issue by linc0380** [yozw/oxdoc#15]
Oxdoc appears to have problems with the `Info()` function of the database class.

The following code is typical of the use of `database`, but can only be compiled by Oxdoc if the line `dbase.Info();` is commented out.
```
#include <oxstd.oxh>
#import <database>

main()
{
    decl dbase = new Database();
    dbase.Create(1, 1, 1, 5, 1);
    dbase.Append(range(1, 5)', "range");
    dbase.Info();
    dbase.Select(0, {"range", 0, 0});
    dbase.SetSelSample(2, 1, 4, 1);
    print(dbase.GetGroup(0));
    delete dbase;
}
```

**Comment by yozw** [comment]
Fixed in https://github.com/yozw/oxdoc/commit/b159eabb48243c1d6de4898a25d1ec833dc9b1d1.
