### ISSUE TITLE
variable names

### ISSUE THREAD

**Issue by linc0380** [yozw/oxdoc#16]
The following code does not compile in Oxdoc:
```
#include <oxstd.h>

main()
{
    decl vdata = rann(10, 1);
    decl in = rows(vdata);
    decl dsigsq = vdata'vdata/in;
    decl df = in*(dsigsq - 1);
    print(df);
}
```
The problem appears to be the name of the variable `in`, since changing it to `cn`, say, does not result in an error.

**Comment by yozw** [comment]
This should now be fixed in https://github.com/yozw/oxdoc/commit/8ab573d5b0d8e63328a0440e5b22f21ba541bca9.
