### ISSUE TITLE
Add root path options to .xml

### ISSUE THREAD

**Issue by ferrall** [yozw/oxdoc#17]
For a large project with separate document folders it's helpful if the CSS and IMG folder location can be varied so that a shared folder can be used:
```
/src
   oxdoc.xml
/src/pack1
  oxdoc.xml
/src/pack2
  oxdoc.xml

/docs
  /css
  /img
  /pack1
      default.html
  /pack2
    default.html
  default.html
  oxdoc.js
``` 
Here there is a main page and two packages with their own documentation.  Rather than have separate /css and /img folders in each, better for them to refer to a relative root and then link <root>/img, <root>/css .  Not sure if js code should be in to be in a dedicated subfolder <root>/js or in root?  

The default is that each folder has its own root specified in outputdir.

But allow in `oxdoc.xml` something like:
...
```
/src/oxdoc.xml
<oxdoc>
  <option outputdir="../doc"/>
  <option rootdir="."/>
  <option javascript="oxdoc.js"/>
</oxdoc>

``` 
For sub folders sharing the same root:
```
/src/pack1/oxdoc.xml
<oxdoc>
  <option outputdir="../doc/pack1"/>
  <option rootdir="../"/>
  <option javascript="oxdoc.js"/>
</oxdoc>
```

**Comment by yozw** [comment]
Do the `csspath` and `imagepath` options not do what you want?

The Javascript, by the way, gets copied verbatim into the html output, so does not need to included in the serving directory. Hence no `js` directory.

**Comment by ferrall** [comment]
Yes, of course! Were those just added? Or did I miss them in the documentation?

**Comment by yozw** [comment]
It's possible that it's not in the manual, but if you run oxdoc without arguments you get an overview of all available configuration options
