### ISSUE TITLE
in now a Ox keyword

### ISSUE THREAD

**Issue by ferrallc** [yozw/oxdoc#4]
"decl in;" creates an OxDoc error but not a syntax error

**Comment by yozw** [comment]
I'm not sure what the expected behaviour is. Is "decl in;" valid Ox code, even though "in" is a keyword?

**Comment by yozw** [comment]
Fixed in https://github.com/yozw/oxdoc/commit/b1adfde4f6ebd34868904615a7fc7e29be1aab4e

**Comment by yozw** [comment]
Hopefully now properly fixed in https://github.com/yozw/oxdoc/commit/8ab573d5b0d8e63328a0440e5b22f21ba541bca9.
